# local GNS3 router
---
loopback_if:
  - name: loopback1337
    desc: Configured with Ansible 
    ip_address: 192.168.161.167/32
    host: 10.10.10.1
    port: 22
    user: admin
    pass: cisco
  - name: loopback1338
    desc: Configured with Ansible 
    ip_address: 192.168.161.168/32
    host: 10.10.10.1
    port: 22
    user: admin
    pass: cisco
  - name: loopback1339
    desc: Configured with Ansible 
    ip_address: 192.168.161.169/32
    host: 10.10.10.1
    port: 22
    user: admin
    pass: cisco