---
- name: Create a loopback
  hosts: gns
  connection: local

  tasks:
    - name: Create interface shell
      with_items: "{{loopback_if}}"
      ios_interface:
        provider:
          host: "{{item.host}}"
          port: "{{item.port}}"
          authorize: yes      
          username: "{{item.user}}"
          password: "{{item.pass}}"
        name: "{{item.name}}"
        description: "{{item.desc}}"
     
    - name: Configure interface
      with_items: "{{loopback_if}}"
      ios_l3_interface:
        name: "{{item.name}}"
        ipv4: "{{item.ip_address}}"
        provider:
          host: "{{item.host}}"
          port: "{{item.port}}"
          authorize: yes      
          username: "{{item.user}}"
          password: "{{item.pass}}"


    