---
- name: Create a loopback
  hosts: group
  connection: local
  tasks:
    - name: Delete interface
      with_items: "{{loopback_if}}"
      ios_command:
        commands:
          - configure terminal
          - "no interface {{item.name}}"
        provider:
          host: "{{item.host}}"
          port: "{{item.port}}"
          authorize: yes      
          username: "{{item.user}}"
          password: "{{item.pass}}"